#tag::security[]
micronaut:
  application:
    name: gateway
  server:
    port: 8080
  security:
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
      #tag::tokenpropagation[]
      propagation:
        enabled: true # <1>
        service-id-regex: "userecho" # <2>
      #end::tokenpropagation[]
  http:
    services:
      userecho:
        urls:
          - "http://localhost:8081"
#end::security[]
