micronaut:
    application:
        name: userecho
    server:
        port: 8081 # <1>
    security:
        enabled: true # <2>
        token:
            jwt:
                enabled: true # <3>
                signatures:
                    secret: # <4>
                        validation:
                            secret: pleaseChangeThisSecretForANewOne # <5>