micronaut:
  application:
    name: userecho
#tag::port[]
---
micronaut:
  server:
    port: 8081 # <1>
#end::port[]
#tag::security[]
---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret: # <1>
            validation:
              secret: pleaseChangeThisSecretForANewOne # <2>
#end::security[]