micronaut:
  application:
    name: userecho
---
endpoints:
  health:
    enabled: true
#tag::port[]
---
micronaut:
  server:
    port: 8081
#end::port[]
---
#tag::security[]
---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
#end::security[]
