micronaut:
  application:
    name: userecho
  server:
    port: 8081
---
#tag::security[]
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
#end::security[]
