#tag::security[]
micronaut:
  application:
    name: userecho
  server:
    port: 8081
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: pleaseChangeThisSecretForANewOne
#end::security[]