Create the microservice:

`mn create-app example.micronaut.gateway`

Add the security-jwt module to the configuration:

[source,groovy]
.build.gradle
----
include::{sourceDir}/../intermediate/gateway/build.gradle[tag=security-jwt,indent=0]
----

To keep this guide simple, create a naive AuthenticationProvider to simulate user’s authentication.

[source,java]
.gateway/src/main/java/example/micronaut/AuthenticationProviderUserPassword.java
----
include::{sourceDir}/../intermediate/gateway/src/main/java/example/micronaut/AuthenticationProviderUserPassword.java[]
----

<1> To register a Singleton in Micronaut’s application context, annotate your class with `javax.inject.Singleton`.
<2> A Micronaut’s Authentication Provider implements the interface `io.micronaut.security.authentication.AuthenticationProvider`.

Create a class `UserController` which exposes `/user` endpoint.

[source,java]
.gateway/src/main/java/example/micronaut/UserController.java
----
include::{sourceDir}/../intermediate/gateway/src/main/java/example/micronaut/UserController.java[]
----

<1> Annotate with `io.micronaut.http.annotation.Controller` to designate a class as a Micronaut’s controller.
<2> Constructor dependency injection
<3> Annotate with `io.micronaut.security.Secured` to configure secured access. The `isAuthenticated()` expression will allow access only to authenticated users.
<4> Since we return a string which is not valid JSON, set the media type to `text/plain`.
<5> You can specify the HTTP verb that a controller's action responds to. To respond to a GET request, use the `io.micronaut.http.annotation.Get` annotation.
<6> You can bind an Http Header to a controller method argument.

Create an interface to encapsulate the collaboration with the `userecho` microservice.

[source,java]
.gateway/src/main/java/example/micronaut/UsernameFetcher.java
----
include::{sourceDir}/../intermediate/gateway/src/main/java/example/micronaut/UsernameFetcher.java[]
----

Create a Micronaut HTTP Declarative client:

[source,java]
.gateway/src/main/java/example/micronaut/UserEchoClient.java
----
include::{sourceDir}/../intermediate/gateway/src/main/java/example/micronaut/UserEchoClient.java[]
----

<1> The `@Client` annotation is used with a service id. We will reference the exact service id in the configuration shortly.
<2> Don't load this bean in the Test environment.
<3> Use `@Get` annotation to define the client mapping
<4> Supply the JWT to the HTTP Authorization header value to the `@Client` method.

Add this snippet to `application.yml` to configure the service url of the `echo` service

[source,yaml]
.gateway/src/main/resources/application.yml
----
include::{sourceDir}/../intermediate/gateway/src/main/resources/application.yml[tags=httpservices]
----

<1> This is the same service ID we used in the `@Client` annotation.
<2> Configure a URL where the `userecho` microservice resides.

Add this snippet to `application.yml` to configure security:

[source,yaml]
.gateway/src/main/resources/application.yml
----
include::{sourceDir}/../intermediate/gateway/src/main/resources/application.yml[tags=security]
----
<1> Set `authentication` to `bearer` to receive a JSON response from the login endpoint.
<2> You can create a SecretSignatureConfiguration named generator via configuration as illustrated above. The generator signature is used to sign the issued JWT claims.
<3> Change this by your own secret and keep it safe (do not store this in your VCS)

=== Tests

Provide a `UsernameFetcher` bean replacement for the Test environment.

[source,java]
.gateway/src/test/java/example/micronaut/UserEchoClientReplacement.java
----
include::{sourceDir}/../intermediate/gateway/src/test/java/example/micronaut/UserEchoClientReplacement.java[]
----

Create a tests which verifies the app is secured and we can access it after login in:

[source,java]
.gateway/src/test/java/example/micronaut/UserControllerTest.java
----
include::{sourceDir}/../intermediate/gateway/src/test/java/example/micronaut/UserControllerTest.java[]
----

<1> Annotate the class with `@MicronautTest` to let Micronaut starts the embedded server and inject the beans. More info: https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html].
<2> Inject the `RxHttpClient` bean in the application context.
<3> Test endpoint is secured