Create the microservice:

`mn create-app example.micronaut.userecho`

Add the security-jwt module to the configuration:

[source,groovy]
.build.gradle
----
include::{sourceDir}/../intermediate/userecho/build.gradle[tag=security-jwt,indent=0]
----

Create a class `UserController` which exposes `/user` endpoint.

[source,java]
.userecho/src/main/java/example/micronaut/UserController.java
----
include::{sourceDir}/../intermediate/userecho/src/main/java/example/micronaut/UserController.java[]
----

<1> Annotate with `io.micronaut.http.annotation.Controller` to designate a class as a Micronaut’s controller.
<2> Annotate with `io.micronaut.security.Secured` to configure secured access. The `isAuthenticated()` expression will allow access only to authenticated users.
<3> Since we return a string which is not valid JSON, set the media type to `text/plain`.
<4> You can specify the HTTP verb that a controller's action responds to. To respond to a GET request, use the `io.micronaut.http.annotation.Get` annotation.
<5> If a user is authenticated, Micronaut will bind the user object to an argument of type `java.security.Principal` (if present).

Add this snippet to `application.yml` to fix the port where `userecho` starts:

[source,yaml]
.userecho/src/main/resources/application.yml
----
include::{sourceDir}/../intermediate/userecho/src/main/resources/application.yml[tags=port]
----

<1> Configure a fix port where the app listens.

Add this snippet to `application.yml`

[source,yaml]
.userecho/src/main/resources/application.yml
----
include::{sourceDir}/../intermediate/userecho/src/main/resources/application.yml[tags=security]
----

<1> You can create a `SecretSignatureConfiguration` named `validation` which is able to validate JWT generated by the `gateway` microservice.
<2> Change this by your own secret and keep it safe (do not store this in your VCS)

