Create the microservice:

`mn create-app example.micronaut.userecho`

Create a class `UserController` which exposes `/user` endpoint.

[source,java]
.userecho/src/main/java/example/micronaut/UserController.java
----
include::{sourceDir}/../intermediate/userecho/src/main/java/example/micronaut/UserController.java[]
----

<1> Annotate with `io.micronaut.http.annotation.Controller` to designate a class as a Micronaut’s controller.
<2> Annotate with `io.micronaut.security.Secured` to configure secured access. The `isAuthenticated()` expression will allow access only to authenticated users.
<3> Since we return a string which is not valid JSON, set the media type to `text/plain`.
<4> You can specify the HTTP verb that a controller's action responds to. To respond to a GET request, use the `io.micronaut.http.annotation.Get` annotation.
<5> If a user is authenticated, Micronaut will bind the user object to an argument of type `java.security.Principal` (if present).

Modify `application.yml`

[source,yaml]
.userecho/src/main/resources/application.yml
----
include::{sourceDir}/../intermediate/userecho/src/main/resources/application.yml[]
----

<1> Configure a fix port where the app listens.
<2> Enable Micronaut’s security capabilities
<3> Expose /login endpoint
<4> Expose /oauth/access_token endpoint as defined by section 6 of the OAuth 2.0 spec - Refreshing an Access Token.
<5> Enable JWT based authentication
<6> You can create a `SecretSignatureConfiguration` named `validation` which is able to validate JWT generated by the `gateway` microservice.
<7> Change this by your own secret and keep it safe (do not store this in your VCS)

